spring:
  application:
    name: stock
  config:
    import: optional:application-secret.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/stock
    username: rst_user
    password: rst_user
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 1000
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off

twelve-data:
  api:
    key: demo