spring:
  application:
    name: stock
  config:
    import: optional:application-secret.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/stock
    username: rst_user
    password: rst_user
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

twelve-data:
  api:
    key: demo

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true